### ISSUE TITLE
Error generating Access Token

### ISSUE THREAD

**Issue by cvaught** [Azure-Samples/active-directory-java-graphapi-web#1]
Thank you for publishing this code.  When trying to use the code I keep getting an error when trying to generate the access token.  I suspect this is due to incorrect parameters in the web.xml file.  Can you provide definition for these values?  For example where do I get the TenantContextID?  I used my Client ID for my application but I don't think that is correct.  I think the Client ID should be AppPrincipalId, is this correct?  For the symmetric key I used the key that was generated for the app in the portal which I think is correct.  What is the AcsPrincipalId and the ProtectedResourcePrincipalId?

**Comment by anotherrohit** [comment]
@RideMo I am seeing this null pointer Can not generate Access Token. I have all the parameters in the web.xml The error seems client_secret.Can you let me know how  i can obtain that for my azuread created app.
