### ISSUE TITLE
thumbnailPhoto property, how to set?

### ISSUE THREAD

**Issue by bitsofinfo** [Azure-Samples/active-directory-java-graphapi-web#3]
How does one set the thumbnailPhoto attribute of a user? The docs say "Edm.Stream" but I have no idea what that translates to for the value in JSON when doing REST. Is that a base64 encoded set of of bytes?

 Please explain

**Comment by jmprieur** [comment]
Please see https://msdn.microsoft.com/en-us/office/office365/api/photo-rest-operations
