### ISSUE TITLE
Getting Message "Insufficient privileges to complete the operation" for all operations on users

### ISSUE THREAD

**Issue by adarshrhegde** [Azure-Samples/active-directory-java-graphapi-web#4]
I have setup the entire code as detailed in the guide. However when I hit the "All Users" api I get the following error message : Error:Authorization_RequestDenied! Insufficient privileges to complete the operation. {"odata.error":{"code":"Authorization_RequestDenied","message":{"lang":"en","value":"Insufficient privileges to complete the operation."}}}  

This is the log I get in tomcat: org.sampleapp.exceptions.SampleAppException: Insufficient privileges to complete the operation.

I have given all permissions through API access to my application in Azure portal under "Required permissions". Any idea why I might be getting this error?

**Comment by nator** [comment]
I get this as well. I wrote an even simpler app to just get the Bearer token and call the Graph API directly, and I get the same error:
{
  "odata.error": {
    "code": "Authorization_RequestDenied",
    "message": {
      "lang": "en",
      "value": "Insufficient privileges to complete the operation."
    }
  }
}

I've checked and double checked the app has permissions and the API Key is good. Hoping this is a recent change that can be worked around? All the similar example apps (PHP, etc) use the same OAuth method so I suspect everything is broken. :(

**Comment by gkhenderson** [comment]
I tried lots of things... setting permissions, roles, etc.    What made this work for me was updating the api-version in web.xml, e.g.

      <init-param>
          <param-name>DataContractVersion</param-name>
          <param-value>api-version=1.5</param-value>
      </init-param>

Now, I get to go back and start fresh to see exactly which few of permissions I added are actually required...  Hopefully this might help someone else with this issue.

**Comment by Walk4Muscle** [comment]
Have you check the permissions on your AAD application against to microsoft graph api? According the document of [List Users](https://graph.microsoft.io/en-us/docs/api-reference/v1.0/api/user_list), we need one of following permission in scope:
>User.ReadBasic.All; User.Read.All; User.ReadWrite.All; Directory.Read.All; Directory.ReadWrite.All; Directory.AccessAsUser.All

You can refer to https://graph.microsoft.io/en-us/docs/authorization/permission_scopes to match the permission name to the scope name.

**Comment by karyaevsm** [comment]
I'm not sure if it would help you, but it had helped me:

Please see here: http://www.morgantechspace.com/2016/01/graph-api-insufficient-privileges-to-complete-the-operation.html

Somehow, this part is not mentioned in MS Tutorial at https://docs.microsoft.com/en-gb/azure/active-directory-b2c/active-directory-b2c-devquickstarts-graph-dotnet.

**Comment by zuckerthoben** [comment]
I want to read groups from Graph and gave my application the application permission Directory.Read.All and Group.Read.All inside the Graph permission. An admin just consented.  
Do I still need to enable "Read directory data" inside Azure Ad permissions? I am using the Graph .Net SDK.

**Comment by vdentice** [comment]
I added the "Read directory data" permission under "Delegated Permissions" for the application registration and it resolved the issue for me.

**Comment by anotherrohit** [comment]
@vdentice Read Directory data already added under Delegated Permissions, have also tried selecting all Application permissions but still see the same error.
@gkhenderson api version selected as 1.5 as well. But no luck.
Any other ideas?

**Comment by AlexJH4U** [comment]
@anotherrohit 

I have run into this same issue.  After working just fine, I started getting the exact unauthorized error message that you received.  

I was able to ultimately resolve the issue by removing "Azure Active Directory" and "Graph API" from the Required Access page and then re-adding it with the appropriate app permissions, and then pressing the Grant Access button to apply them.  After this, and waiting 5 minutes for propagation, it went through just fine.

My only guess is that this was caused for my by some sort of propagation delay.  I made quite a few tweaks to the Required Permissions before it started working correctly.  Perhaps there was some sort of a race condition, and one of my Saves ended up overwriting the correct app permissions after-the-fact.  Just speculation.

For whatever reason, re-adding the API's and regranting the permissions worked for me.  

Hope this helps!

Alex

**Comment by tomleetaiwan** [comment]
Hi Alex,
I have the same issue and I follow your suggestion, to remove "Azure Active Directory" and "Graph API" from the Required Access page and then re-adding it with the appropriate app permissions, it works fine ! 
Best Regards,
Tom
